### ISSUE TITLE
CMakeLists does not respect CMAKE_INSTALL_PREFIX

### ISSUE THREAD

**Issue by danieldjewell** [martinellimarco/t2sz#2]
Line 15 in CMakeLists hardcodes an install prefix which does not respect the CMAKE_INSTALL_PREFIX variable. 

https://github.com/martinellimarco/t2sz/blob/72bf850e54f8a73c8c9cd025b5aeccd0a39b02bd/CMakeLists.txt#L15

Changing this to:

```cmake
install(TARGETS t2sz)
```

corrects the problem and allows cmake to utilize the specified install prefix.

**Comment by martinellimarco** [comment]
You are correct, it will be fixed soon. Thank you!
